# Generated by Django 3.1.1 on 2020-09-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200920_1853_squashed_0006_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'Member'), (2, 'Admin')]),
        ),
    ]
