# Generated by Django 3.1.1 on 2020-09-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200922_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'Member'), (2, 'Admin')], default=1),
        ),
    ]
