# Generated by Django 3.1.1 on 2020-09-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('boards', '0003_auto_20200923_1024'), ('boards', '0004_auto_20200923_1028'), ('boards', '0005_auto_20200923_1030')]

    dependencies = [
        ('boards', '0002_auto_20200920_2158'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='owner_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='owner_model',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'users'), ('model', 'user')), models.Q(('app_label', 'projects'), ('model', 'project')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='board', to='contenttypes.contenttype'),
        ),
    ]
