# Generated by Django 3.1.1 on 2020-09-24 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0003_auto_20200923_1024_squashed_0005_auto_20200923_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
