# Generated by Django 3.1.2 on 2020-10-19 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('boards', '0006_auto_20201019_1644'), ('boards', '0007_auto_20201019_1644')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0005_notification_squashed_0007_auto_20201014_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='owner_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
