# Generated by Django 3.1.2 on 2020-10-20 11:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('boards', '0007_starredboard'), ('boards', '0008_delete_starredboard')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0006_auto_20201019_1644_squashed_0007_auto_20201019_1644'),
    ]

    operations = [
    ]
