# Generated by Django 3.1.2 on 2020-10-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
