# Generated by Django 3.1.2 on 2020-10-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20201022_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='color',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='board',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
