# Generated by Django 3.1.2 on 2020-10-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20201022_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='labels',
            field=models.ManyToManyField(blank=True, to='boards.Label'),
        ),
        migrations.AddField(
            model_name='label',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='boards.board'),
            preserve_default=False,
        ),
    ]
