# Generated by Django 3.1.2 on 2020-10-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_auto_20201022_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
