# Generated by Django 3.1.2 on 2020-10-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_delete_starredboard'),
        ('users', '0002_auto_20200921_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='starred_boards',
            field=models.ManyToManyField(blank=True, to='boards.Board'),
        ),
    ]
